#ifndef MUSIC_ANNOTATOR_GLOBAL_H
#define MUSIC_ANNOTATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MUSIC_ANNOTATOR_LIBRARY)
#  define MUSIC_ANNOTATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MUSIC_ANNOTATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MUSIC_ANNOTATOR_GLOBAL_H
